version: "3.8"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./:/my-app
      - /my-app/node_modules
    stdin_open: true
    tty: true